### ISSUE TITLE
module 'pydantic._internal._typing_extra' has no attribute 'add_module_globals'

### ISSUE THREAD

**Issue by bndr** [websideproject/django-paddle-billing#113]
## 🐛 Bug Report

AttributeError
module 'pydantic._internal._typing_extra' has no attribute 'add_module_globals'

## 🔬 How To Reproduce

1. Import paddle client directly that is included in this package
from paddle_billing_client.client import PaddleApiClient

## 📎 Additional context

<img width="592" alt="AttributeError: module 'pydantic _internal _typing_extra' has no attribute 'add_module_globals' — mindnow-ag — vadim-play-proje… 2024-09-06 18-30-31" src="https://github.com/user-attachments/assets/ac6e92b3-7adf-41a5-896e-cc5f9ffb42af">

**Comment by bndr** [comment]
I had to downgrade pydantic package to bring everything back up, not sure what's wrong with that one.

`pydantic-core==2.18.4`

**Comment by bgervan** [comment]
Thank for the notification.

Yes, something changed with pydantic 2.8, pydantic==2.7.4 work just fine. I will need to take a look what's changed and update the paddle billing package. I will fix the pydantic version once I found the issue so later it won't break again.

**Comment by bgervan** [comment]
The root cause is in the api-client-pydantic pacakge, it limits the pydantic version with 3.0.0, and in 2.9.0 they changes something that breaks the package. I have added the pydantic deps in paddle-billing-client and set the hard limit with 2.8.2 for now.

**Comment by ddorian** [comment]
@bgervan this has been fixed in https://github.com/mom1/api-client-pydantic/issues/406 so you can fix the version constraint too.

**Comment by bgervan** [comment]
I have upgraded the deps on the api client package. If you update your deps, it should work now

**Comment by ddorian** [comment]
It works, thank you!
