### ISSUE TITLE
chargeback_reverse missing, webhook fails

### ISSUE THREAD

**Issue by bndr** [websideproject/django-paddle-billing#125]
<img width="568" alt="ValidationError: 1 validation error for NotificationPayload action Input should be 'refund', 'credit', 'chargeback' or 'chargeb… 2024-09-23 14-59-38" src="https://github.com/user-attachments/assets/cb404019-5a41-42fa-b28c-04a42efc452c">

**Comment by bgervan** [comment]
I have updated the Paddle billing client with several missing stuff in Adjustment. 

Let me know if it solved your particular issue.

**Comment by bndr** [comment]
I confirm all is good now. Thanks a lot for quick response!
