### ISSUE TITLE
Error syncing discounts from Paddle sandbox

### ISSUE THREAD

**Issue by dnovikov** [websideproject/django-paddle-billing#138]
## 🐛 Bug Report

Error syncing discounts from Paddle sandbox

## 🔬 How To Reproduce

1. Create a product and a discount for it in a Paddle sandbox
2. Run `python manage.py sync_from_paddle`

### Code sample

---

### Environment

* OS: Linux
* Python version, get it with:

3.11

### Screenshots

![image](https://github.com/user-attachments/assets/b5f1f9ab-12d6-4c3f-99a8-916c4f553cec)

## 📈 Expected behavior

Discounts are synced.

## 📎 Additional context

---

**Comment by bgervan** [comment]
I have updated the paddle billing client so discount code can be null now. Update it to https://github.com/websideproject/paddle-billing-client/releases/tag/v0.2.17

**Comment by dnovikov** [comment]
`Successfully synced data from Paddle`

Works like a charm now, thank you @bgervan so much!
