### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by benhowes** [websideproject/django-paddle-billing#36]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/bgervan/paddle-billing-client/issues?q=is%3Aissue).

## ❓ Question

I've been having a browse through this repo and https://github.com/websideproject/paddle-billing-client. The other repo mentions that this project is WIP. Looking through the code it seems like the majority of what's required is in place?

Are you using the code on a live project?

Thanks!

**Comment by bgervan** [comment]
Hi, 
thanks for reaching out. 

Except a few helper function and better examples it's ready to go. I am not using it yet, but I am building a saas blueprint where I will. When I have time to add some docs and better example, I will remove the WIP from the client readme. 

Feel free to ask usage questions here, I will try to response as I can.

**Comment by benhowes** [comment]
Thanks, that's great to know!
