### ISSUE TITLE
Status choices for Subscriptions

### ISSUE THREAD

**Issue by acalderon85** [websideproject/django-paddle-billing#51]
## 🐛 Bug Report

Hello, 

I am planning on using this library for integrating Paddle with my Django app.

I was reading the code and I noticed this:

According to Paddle's documentation (https://developer.paddle.com/api-reference/subscriptions/get-subscription), the possible statuses for Subscriptions are: 

- active
- canceled
- past_due
- paused
- trialing

Instead, we have the following in the Subscription model:

### models.py

    status = models.CharField(
        max_length=10,
        choices=[
            ("active", "Active"),
            ("trialing", "Trialing"),
            ("paused", "Paused"),
            ("deleted", "Deleted"),
        ],
    )

Will this fail or cause problems when syncing subscriptions with 'past_due' or 'canceled' statuses?

Thanks.

**Comment by bgervan** [comment]
Hello, 

thanks for the report. I have fixed and published a new release with the fix.

https://pypi.org/project/django-paddle-billing/0.1.3/

Feel free to report any issue during the integration.
