### ISSUE TITLE
transaction.ready webhook missing from SUPPORTED_WEBHOOKS

### ISSUE THREAD

**Issue by DeeeeLAN** [websideproject/django-paddle-billing#59]
See here:

https://github.com/websideproject/django-paddle-billing/blob/4a87c501288984e4552e294acae82611ced37e5a/src/django_paddle_billing/views.py#L61-L69

Compared to the list of webhooks on the paddle destination page:

![image](https://github.com/websideproject/django-paddle-billing/assets/12877032/892abfad-3f1a-46f9-b05c-945d5949660a)

**Comment by bgervan** [comment]
Thanks, I have added.

Fixed in v0.1.5
