### ISSUE TITLE
Unable to get through contributing setup steps

### ISSUE THREAD

**Issue by DeeeeLAN** [websideproject/django-paddle-billing#60]
`make install` works fine. 
`make pre-commit-install` fails, `pre-commit: command not found`

It looks like the pyproject.toml file is set up with hatch, despite the documentation stating we are using poetry for dependencies.

I tried installing pre-commit manually, but `poetry shell` failed, it doesn't like the pyproject.toml file in its current form.

**Comment by bgervan** [comment]
The readme doesn't mention poetry. I am using poetry for the paddle billing client (that's how the makefile contains many unused stuff for now), this package uses hatch. 
To install dependencies, there is a generated requirements.txt to make it easier. 

Via pip-tools, you can refresh it in case you need
`pip-compile --output-file=requirements.txt pyproject.toml`

To install the local package in a example, you can check the requirements.txt for the example. 

```
paddle-billing-client==0.2.4
django-ninja==1.1.0
# django-paddle-billing
-e ../../
```

**Comment by bgervan** [comment]
I see the Contribution.ms contains wrong information, I will update it

**Comment by DeeeeLAN** [comment]
Thanks, I will give it a try now.
